<a href="https://colab.research.google.com/github/Nohan28/cie-3/blob/main/cie_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [21]:
x=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=df[['Species']]

In [24]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [23]:
y

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [7]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
108            6.7           2.5            5.8           1.8
50             7.0           3.2            4.7           1.4
87             6.3           2.3            4.4           1.3
4              5.0           3.6            1.4           0.2
76             6.8           2.8            4.8           1.4
..             ...           ...            ...           ...
140            6.7           3.1            5.6           2.4
148            6.2           3.4            5.4           2.3
81             5.5           2.4            3.7           1.0
62             6.0           2.2            4.0           1.0
8              4.4           2.9            1.4           0.2

[120 rows x 4 columns]

In [8]:
x_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
84             5.4           3.0            4.5           1.5
59             5.2           2.7            3.9           1.4
126            6.2           2.8            4.8           1.8
29             4.7           3.2            1.6           0.2
24             4.8           3.4            1.9           0.2
93             5.0           2.3            3.3           1.0
7              5.0           3.4            1.5           0.2
28             5.2           3.4            1.4           0.2
71             6.1           2.8            4.0           1.3
9              4.9           3.1            1.5           0.1
32             5.2           4.1            1.5           0.1
78             6.0           2.9            4.5           1.5
111            6.4           2.7            5.3           1.9
75             6.6           3.0            4.4           1.4
38             4.4           3.0            1.3           0.2
12             4.8           3.0            1.4           0.1
15             5.7           4.4            1.5           0.4
67             5.8           2.7            4.1           1.0
69             5.6           2.5            3.9           1.1
54             6.5           2.8            4.6           1.5
98             5.1           2.5            3.0           1.1
145            6.7           3.0            5.2           2.3
79             5.7           2.6            3.5           1.0
80             5.5           2.4            3.8           1.1
23             5.1           3.3            1.7           0.5
73             6.1           2.8            4.7           1.2
117            7.7           3.8            6.7           2.2
72             6.3           2.5            4.9           1.5
115            6.4           3.2            5.3           2.3
60             5.0           2.0            3.5           1.0

In [9]:
y_train

Species
108   Iris-virginica
50   Iris-versicolor
87   Iris-versicolor
4        Iris-setosa
76   Iris-versicolor
..               ...
140   Iris-virginica
148   Iris-virginica
81   Iris-versicolor
62   Iris-versicolor
8        Iris-setosa

[120 rows x 1 columns]

In [10]:
y_test

Species
84   Iris-versicolor
59   Iris-versicolor
126   Iris-virginica
29       Iris-setosa
24       Iris-setosa
93   Iris-versicolor
7        Iris-setosa
28       Iris-setosa
71   Iris-versicolor
9        Iris-setosa
32       Iris-setosa
78   Iris-versicolor
111   Iris-virginica
75   Iris-versicolor
38       Iris-setosa
12       Iris-setosa
15       Iris-setosa
67   Iris-versicolor
69   Iris-versicolor
54   Iris-versicolor
98   Iris-versicolor
145   Iris-virginica
79   Iris-versicolor
80   Iris-versicolor
23       Iris-setosa
73   Iris-versicolor
117   Iris-virginica
72   Iris-versicolor
115   Iris-virginica
60   Iris-versicolor

In [11]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [12]:
y_pred=dtc.predict(x_test)
print(y_pred)

['Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor']


In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
acc=accuracy_score(y_test,y_pred)
print('accuracy',acc)
cm= confusion_matrix(y_test,y_pred)
print('confusion_matrix\n',cm)
cr=classification_report(y_test,y_pred)
print('classification_report',cr)

accuracy 0.9666666666666667
confusion_matrix
 [[10  0  0]
 [ 0 14  1]
 [ 0  0  5]]
classification_report                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.93      0.97        15
 Iris-virginica       0.83      1.00      0.91         5

       accuracy                           0.97        30
      macro avg       0.94      0.98      0.96        30
   weighted avg       0.97      0.97      0.97        30

